version: 2

project_name: etcd-tui

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=0

builds:
  - id: etcd-tui
    binary: etcd-tui
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '6'
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -s -w -X main.commit={{.Commit}}
      - -s -w -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

brews:
  - name: etcd-tui
    commit_author:
      name: aleksandersh
      email: alex-shuttle@yandex.ru
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/aleksandersh/etcd-tui/"
    description: "Terminal user interface for etcd"
    license: "MIT"
    repository:
      owner: aleksandersh
      name: homebrew-etcd-tui
      branch: main
    test: |
      system "#{bin}/etcd-tui --version"
